Feat/remove keymaps
phaazon/mind.nvim pull request #38
Opened 2022-08-25 16:54 UTC by krleitch

To easily remove unwanted keymaps add the option keymaps.remove_keymaps.
This option defaults to false and will do nothing.

Some people don't want any keymaps set. In this case set to true.
```
remove_keymaps = true
```

If you just want to disable a select few, provide a list
```
remove_keymaps = {"<tab>", "q"}
```

If you override a keymap but also include it in remove_keymaps then the key will still not be set.

2022-08-25 21:12 UTC, phaazon requested changes
May you rebase on `master` and not use merge commits? Thanks in advance

2022-09-01 22:07 UTC, phaazon requested changes
> `remove_keymaps = {"<tab>", "q"}`

I don’t like that, it seems super weird. Either people use the default keymaps, or they don’t. If they want to just remove a single keymap, they can set the key to `nil` in their configuration. Basically, removing default keymaps should just be a boolean in the config set to `true` automatically, like `default_keymaps`.

2022-09-02 19:04 UTC, krleitch commented
Updated as suggested to use `keymaps.default_keymaps` however setting keymaps to `nil` does not work as intended. When `vim.tbl_deep_extend('force', defaults, opts or {})` is called if a keymap is set to nil in opts it is skipped and the default is still applied. I'm not sure how to prevent this behavior using `nil`. As a possible solution I made it if you set the keymap to `'nil'` it will not apply the map. I also had to change `insert_keymaps` in `keymap.lua` to not overwrite a keymap that was set to `'nil'`. I'm not a fan of using `'nil'` but if a key is set to nil it doesn't exist in the table to overwrite the default. Another options would be using `false` but I'm not sure if that makes more sense.

2023-03-22 23:03 UTC, phaazon commented
Thanks for considering contributing, but I’m going to archive `mind.nvim`.

2023-03-22 23:03 UTC, closed without merging