Hide relative line numbers in mind buffer
phaazon/mind.nvim pull request #66
Opened 2022-11-06 10:20 UTC by aniketgm

# Issue
If someone like me sets relative line numbering, they are displayed in the mind buffer. I've added this code to hide those relative numbering.

## Before Changes
![mind_nvim_before_changes](https://user-images.githubusercontent.com/14215698/200165390-21e5c1e2-3bb7-4c83-8e8f-eaa039468498.png)

## After Changes
![mind_nvim_after_changes](https://user-images.githubusercontent.com/14215698/200165403-628f5ffa-5c76-4382-8748-f7c8f8d2984a.png)

2022-12-07 00:11 UTC, phaazon requested changes

2022-12-07 00:11 UTC, phaazon commented on lua/mind/ui.lua
> +local mind_node = require 'mind.node'
No need to change that, please.

2022-12-07 15:42 UTC, aniketgm commented on lua/mind/ui.lua
> +local mind_node = require 'mind.node'
sure. This was done by the lua autoformat (lua lsp i guess). I don't think this will cause any issues. But anyways, I'll revert these changes.

2022-12-09 13:51 UTC, phaazon approved these changes
Thanks!

2022-12-09 13:51 UTC, merged